### ISSUE TITLE
gndc - Stage 3 - Plan subroutines & data flow

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/gnd#166]
**Prompt 3A – Pipeline planner**

```
You are a Gendo planner. Using the opcode list and
clarified routine, break the implementation into
high-level subroutines. For each subroutine give:
  * name
  * brief purpose
  * inputs (array indices or names)
  * output (value in _)
  * opcodes used (subset of list)

Return as YAML under a key subs.

Clarified routine:
<<< {clarified_text} >>>

Required ops:
<<< {ops_yaml} >>>
```

**Expected output**

```yaml
subs:
  - name: load-inputs
    purpose: Bind arguments to variables.
    inputs: ["_ (args array)"]
    output: last bound var
    ops: [index, let]

  - name: compute-checksum
    purpose: Sum numbers then int-cast.
    inputs: [numbers list]
    output: checksum int
    ops: [map, int]

  - name: format-result
    purpose: Build final string.
    inputs: [checksum]
    output: formatted string
    ops: [concat]

  - name: main
    purpose: glue; calls others; exits.
    inputs: args array
    output: result string
    ops: [code, exec, exit, if]
```

---
